// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABC9UyYyuqdeRPE8QvuXW2UeScrvaaYpY',
    appId: '1:505906125206:web:bcc35b82b119bc021125b7',
    messagingSenderId: '505906125206',
    projectId: 'parcial-3-3fa1a',
    authDomain: 'parcial-3-3fa1a.firebaseapp.com',
    storageBucket: 'parcial-3-3fa1a.appspot.com',
    measurementId: 'G-HH5TLKF1K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAqBX_eb7MbbWDl1eyMh32x5ATTke_nN4',
    appId: '1:505906125206:android:cbb618b370d72e931125b7',
    messagingSenderId: '505906125206',
    projectId: 'parcial-3-3fa1a',
    storageBucket: 'parcial-3-3fa1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkIU4ywAvUBFaTXZOVhv9yWf0wbyaBLok',
    appId: '1:505906125206:ios:c93d0fc6749e2d7e1125b7',
    messagingSenderId: '505906125206',
    projectId: 'parcial-3-3fa1a',
    storageBucket: 'parcial-3-3fa1a.appspot.com',
    iosBundleId: 'com.example.tercerParcial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkIU4ywAvUBFaTXZOVhv9yWf0wbyaBLok',
    appId: '1:505906125206:ios:c93d0fc6749e2d7e1125b7',
    messagingSenderId: '505906125206',
    projectId: 'parcial-3-3fa1a',
    storageBucket: 'parcial-3-3fa1a.appspot.com',
    iosBundleId: 'com.example.tercerParcial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABC9UyYyuqdeRPE8QvuXW2UeScrvaaYpY',
    appId: '1:505906125206:web:ae0c6d77e33597b01125b7',
    messagingSenderId: '505906125206',
    projectId: 'parcial-3-3fa1a',
    authDomain: 'parcial-3-3fa1a.firebaseapp.com',
    storageBucket: 'parcial-3-3fa1a.appspot.com',
    measurementId: 'G-3ZVWXY8VC5',
  );
}
