// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBADJzoR3coGFvHt9OMjd0bl34FwPZ16o4',
    appId: '1:1044464958375:web:45218dcce55ce94fd05482',
    messagingSenderId: '1044464958375',
    projectId: 'tercer-parcial-redo',
    authDomain: 'tercer-parcial-redo.firebaseapp.com',
    storageBucket: 'tercer-parcial-redo.appspot.com',
    measurementId: 'G-R5202QS4Q4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwySvENIDoxdqhbYqoQ3Ry54l0uOX-VMw',
    appId: '1:1044464958375:android:50e7c0d58bde1223d05482',
    messagingSenderId: '1044464958375',
    projectId: 'tercer-parcial-redo',
    storageBucket: 'tercer-parcial-redo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgfJwko0rOtnB97gdBmh02dDmUxI3Wyvg',
    appId: '1:1044464958375:ios:68437bd852d5d249d05482',
    messagingSenderId: '1044464958375',
    projectId: 'tercer-parcial-redo',
    storageBucket: 'tercer-parcial-redo.appspot.com',
    iosBundleId: 'com.example.tercerParcial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgfJwko0rOtnB97gdBmh02dDmUxI3Wyvg',
    appId: '1:1044464958375:ios:68437bd852d5d249d05482',
    messagingSenderId: '1044464958375',
    projectId: 'tercer-parcial-redo',
    storageBucket: 'tercer-parcial-redo.appspot.com',
    iosBundleId: 'com.example.tercerParcial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBADJzoR3coGFvHt9OMjd0bl34FwPZ16o4',
    appId: '1:1044464958375:web:f2728943919544f1d05482',
    messagingSenderId: '1044464958375',
    projectId: 'tercer-parcial-redo',
    authDomain: 'tercer-parcial-redo.firebaseapp.com',
    storageBucket: 'tercer-parcial-redo.appspot.com',
    measurementId: 'G-E2KSQCELX8',
  );
}
